// SPDX-License-Identifier: GPL-2.0-only
//! Make TUI/CLI settings survive reboots via systemd oneshots that re-apply the
//! saved config at boot. aputune already runs as root (SMU/SMN access), so it
//! writes the unit files and drives systemctl directly.
//!
//! Each tunable domain persists its own config file and has a boot unit that
//! re-applies it:
//!
//! * CPU OC  -> /var/lib/aputune/cpu.json   (arieltune-cpu-oc.service)
//! * CU route-> /var/lib/aputune/route.json (arieltune-route.service; also used
//!   by the existing hand-installed unit)
//!
//! GPU power (manual pin / governor / autosleep / released) persists via
//! dpm::PowerConfig + ONE always-enabled unit (arieltune-gpu.service) whose
//! `gpu apply-boot` dispatches on power.json — see the GPU section below. Units
//! generated here shell out to `/usr/local/bin/arieltune apu <...>` (the suite
//! binary + the `apu` tab's CLI), not the old standalone `aputune`.

use std::path::Path;
use std::process::{Command, Stdio};

use anyhow::{ensure, Context, Result};

const UNIT_DIR: &str = "/etc/systemd/system";

fn systemctl(args: &[&str]) -> Result<()> {
    // Silence stdout/stderr: systemctl's "Created symlink"/"Removed"/"Failed to
    // disable" chatter would otherwise splatter onto the ratatui TUI screen.
    let st = Command::new("systemctl")
        .args(args)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .with_context(|| format!("run systemctl {args:?}"))?;
    ensure!(st.success(), "systemctl {:?} failed ({st})", args);
    Ok(())
}

/// Append a one-line audit record of a GPU power-mode transition to
/// /var/lib/aputune/transitions.log. aputune silences all systemctl chatter (so
/// it doesn't splatter the TUI), which also means its own mode changes leave no
/// trace — this restores one. Best-effort; never fails the caller.
pub fn log_transition(action: &str) {
    use std::io::Write;
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    if let Ok(mut f) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open("/var/lib/aputune/transitions.log")
    {
        let _ = writeln!(f, "{ts} {action}");
    }
}

/// Install (write + daemon-reload + enable) a boot unit. Idempotent.
fn install_enable(unit: &str, body: &str) -> Result<()> {
    let path = format!("{UNIT_DIR}/{unit}");
    std::fs::write(&path, body).with_context(|| format!("write {path} (need root)"))?;
    systemctl(&["daemon-reload"])?;
    systemctl(&["enable", unit])?;
    Ok(())
}

/// Disable + remove a boot unit. Best-effort (never errors on a missing unit).
fn disable_remove(unit: &str) {
    let _ = systemctl(&["disable", unit]);
    let _ = std::fs::remove_file(format!("{UNIT_DIR}/{unit}"));
    let _ = systemctl(&["daemon-reload"]);
}

fn enabled(unit: &str) -> bool {
    Command::new("systemctl")
        .args(["is-enabled", "--quiet", unit])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

// ---- CPU OC ----

pub const CPU_OC_UNIT: &str = "arieltune-cpu-oc.service";

fn cpu_oc_unit_text() -> String {
    "# AUTO-GENERATED by arieltune. Re-applies the persisted CPU OC (cpu.json) at\n\
     # boot via the SMU queue-3 mailbox. `arieltune apu cpu restore` removes it.\n\
     [Unit]\n\
     Description=arieltune CPU OC re-apply (SMU queue 3)\n\
     After=multi-user.target\n\
     \n\
     [Service]\n\
     Type=oneshot\n\
     RemainAfterExit=yes\n\
     # Boot-settle delay (see governor unit) before actuating the SMU.\n\
     ExecStartPre=/usr/bin/sleep 60\n\
     ExecStart=/usr/local/bin/arieltune apu cpu apply-saved\n\
     \n\
     [Install]\n\
     WantedBy=multi-user.target\n"
        .to_string()
}

/// Install + enable the CPU-OC re-apply service so the saved OC survives reboots.
pub fn enable_cpu_oc() -> Result<()> {
    install_enable(CPU_OC_UNIT, &cpu_oc_unit_text())
}

/// Remove the CPU-OC re-apply service.
pub fn disable_cpu_oc() {
    disable_remove(CPU_OC_UNIT)
}

pub fn cpu_oc_enabled() -> bool {
    enabled(CPU_OC_UNIT)
}

// ---- CU routing ----

pub const ROUTE_UNIT: &str = "arieltune-route.service";

fn route_unit_text() -> String {
    "# AUTO-GENERATED by arieltune. Re-applies the saved CU routing (route.json) at\n\
     # boot. `arieltune apu cu route-all` + removing the unit reverts.\n\
     [Unit]\n\
     Description=arieltune CU routing re-apply (umr)\n\
     After=multi-user.target\n\
     \n\
     [Service]\n\
     Type=oneshot\n\
     RemainAfterExit=yes\n\
     # Boot-settle delay (see governor unit) before touching the SPI route.\n\
     ExecStartPre=/usr/bin/sleep 60\n\
     ExecStart=/usr/local/bin/arieltune apu cu route-load\n\
     \n\
     [Install]\n\
     WantedBy=multi-user.target\n"
        .to_string()
}

/// Install + enable the CU-routing re-apply service (used after a route-save).
pub fn enable_route() -> Result<()> {
    install_enable(ROUTE_UNIT, &route_unit_text())
}

pub fn disable_route() {
    disable_remove(ROUTE_UNIT)
}

pub fn route_enabled() -> bool {
    enabled(ROUTE_UNIT)
}

// ---- GPU power (ONE always-enabled unit, dispatched on power.json) ----
//
// Historically GPU power was three competing boot units (aputune-gpu-clock /
// aputune-gpu-governor / aputune-autosleep) that enabled/disabled each other on
// every mode change. That "unit A deleted / unit B enabled" drift class is how
// a heat-pin died. Now there is exactly ONE unit, always installed + enabled;
// `gpu apply-boot` reads power.json and enacts the persisted mode. Mode changes
// only edit power.json and restart this unit.

pub const GPU_UNIT: &str = "arieltune-gpu.service";

/// Competing GPU-power units the double-writer guard must detect -- ANY of these
/// being enabled means a second SMU clock writer could exist, so `apply-boot`
/// refuses to (re-)force the clock (`any_legacy_gpu_unit_enabled`). This list
/// spans BOTH eras so a half-migrated box is safe:
///   * the aputune pre-single-unit per-mode units (the original drift class);
///   * the OLD aputune single unit `aputune-gpu.service` -- the M5 rename
///     supersedes it, but if aputune is still installed alongside arieltune its
///     unit is a live second writer, so it MUST be caught here;
///   * the arieltune-era per-mode names -- never generated now, but kept in the
///     guard too so a future revision that splits the unit again can't sneak a
///     second writer past this check.
///
/// It deliberately does NOT include the current `GPU_UNIT` (`arieltune-gpu`),
/// which is always enabled -- listing it would make the guard always fire.
const LEGACY_GPU_UNITS: [&str; 7] = [
    // aputune pre-single-unit per-mode units
    "aputune-gpu-clock.service",
    "aputune-gpu-governor.service",
    "aputune-autosleep.service",
    // OLD aputune single unit (superseded by arieltune-gpu.service)
    "aputune-gpu.service",
    // arieltune-era per-mode names (never generated now; future-proofing)
    "arieltune-gpu-clock.service",
    "arieltune-gpu-governor.service",
    "arieltune-autosleep.service",
];

fn gpu_unit_text() -> String {
    "# AUTO-GENERATED by arieltune. THE one GPU power unit: `gpu apply-boot` reads\n\
     # power.json and enacts the persisted mode (manual pin / governor /\n\
     # autosleep / released). Mode changes edit power.json + restart this unit —\n\
     # it is never disabled.\n\
     [Unit]\n\
     Description=arieltune GPU power (manual pin or auto governor, per power.json)\n\
     After=multi-user.target\n\
     \n\
     [Service]\n\
     Type=simple\n\
     # The manual/released branches exit 0 once applied; RemainAfterExit keeps\n\
     # the unit active (exited) and Restart=on-failure won't restart an exit-0.\n\
     RemainAfterExit=yes\n\
     Restart=on-failure\n\
     RestartSec=5\n\
     # With Type=simple the start job completes immediately, so no start\n\
     # timeout gates the boot-settle wait inside apply-boot. TimeoutStartSec is\n\
     # kept as belt-and-braces for any future Type change (a finite timeout\n\
     # flapped the old Type=oneshot units without reaching steady state).\n\
     TimeoutStartSec=infinity\n\
     ExecStart=/usr/local/bin/arieltune apu gpu apply-boot\n\
     \n\
     [Install]\n\
     WantedBy=multi-user.target\n"
        .to_string()
}

/// Disable + delete the legacy per-mode GPU units (migration). Best-effort.
fn remove_legacy_units() {
    for u in LEGACY_GPU_UNITS {
        let _ = systemctl(&["disable", "--now", u]);
        let _ = std::fs::remove_file(format!("{UNIT_DIR}/{u}"));
    }
    let _ = systemctl(&["daemon-reload"]);
}

/// Install + enable the single GPU power unit, then migrate off the legacy
/// per-mode units. Idempotent; always rewrites the unit text so fixes propagate.
pub fn ensure_gpu_unit() -> Result<()> {
    install_enable(GPU_UNIT, &gpu_unit_text())?;
    remove_legacy_units();
    Ok(())
}

/// Make the persisted power.json mode authoritative: ensure the single unit is
/// installed + enabled, then restart it (the restart stops any running
/// governor/autosleep daemon and re-enacts the saved mode). Callers do the live
/// SMU action first for instant effect; this makes it stick.
pub fn apply_mode() -> Result<()> {
    ensure_gpu_unit()?;
    restart_gpu_unit();
    Ok(())
}

/// Restart the GPU power unit (re-enacts power.json). Best-effort.
pub fn restart_gpu_unit() {
    let _ = systemctl(&["restart", GPU_UNIT]);
}

/// Transiently stop GPU power management (e.g. to hard-pin the clock for a
/// benchmark) WITHOUT touching enablement or power.json — `start_gpu_unit`
/// resumes the persisted mode. Also stops any legacy unit still running on an
/// un-migrated host, so a bench never races a second SMU writer (wedge class).
pub fn stop_gpu_unit() {
    let _ = systemctl(&["stop", GPU_UNIT]);
    for u in LEGACY_GPU_UNITS {
        let _ = systemctl(&["stop", u]);
    }
}

/// Resume GPU power management after `stop_gpu_unit`: start the single unit
/// (apply-boot re-enacts the persisted mode — a manual pin comes back pinned).
/// On an un-migrated host, restart whichever legacy units are still enabled.
pub fn start_gpu_unit() {
    let _ = systemctl(&["start", GPU_UNIT]);
    for u in LEGACY_GPU_UNITS {
        if enabled(u) {
            let _ = systemctl(&["start", u]);
        }
    }
}

/// Restart the GPU unit only in AUTO mode (no manual pin) — used after a
/// governor tier/config edit so the running daemon rereads it. A manual pin is
/// left completely undisturbed (heat-safety: never churn a pinned clock).
pub fn reload_if_auto() {
    if crate::dpm::PowerConfig::load_or_default()
        .force_mhz
        .is_none()
    {
        restart_gpu_unit();
    }
}

/// Is the single GPU power unit installed (its file present)? Used by the
/// voltage paths to report honestly whether a saved Vid will re-apply at boot.
pub fn gpu_unit_installed() -> bool {
    Path::new(&format!("{UNIT_DIR}/{GPU_UNIT}")).exists()
}

/// Is ANY legacy GPU unit still enabled (un-migrated host)? This is the guard
/// apply-boot uses for BOTH the manual and auto branches — a legacy governor OR
/// autosleep unit is a competing SMU writer either way.
pub fn any_legacy_gpu_unit_enabled() -> bool {
    LEGACY_GPU_UNITS.iter().any(|u| enabled(u))
}

/// Is the GPU power unit currently active (running or exited-held)? Used by the
/// TUI mode row to flag a power.json that CLAIMS governor while nothing runs.
pub fn gpu_unit_active() -> bool {
    Command::new("systemctl")
        .args(["is-active", "--quiet", GPU_UNIT])
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}
